default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASSWORD'] %>

development:
  <<: *default
  database: <%= ENV['HEROKU_DATABASE'] || ENV['PG_DATABASE_NAME'] %>_development

test:
  <<: *default
  database: <%= ENV['HEROKU_DATABASE'] || ENV['PG_DATABASE_NAME'] %>_test

production:
  <<: *default
  database: <%= ENV['HEROKU_DATABASE'] || ENV['PG_DATABASE_NAME'] %>
  port: 5432
  username: <%= ENV['HEROKU_DATABASE_USER'] || ENV['PG_USER'] %>
  password: <%= ENV['HEROKU_DATABASE_PASSWORD'] || ENV['PG_USER'] %>
